---
- hosts: all
  become: yes
  vars_files:
    - vault/geoip_vars.yml
  vars:
    - use_proxy: no
    - proxy_ip: x.x.x.x
    - proxy_port: 3128
    - zeek_ver: zeek-4.0.1
      # select the branch version of zeek to install      
    - repo_branch: 'release/4.0'
    - digest_salt: h3ll0fr3ind
    - enable_json: yes  
    - logdir: /zeek
    - zeekdir: /opt

    # UFW variables
    - ports_allowed:
      - port: ssh
      - port: 9997
        proto: tcp
      - port: 9996
        proto: tcp
      - port: 8000
        proto: tcp
      - port: 8089
        proto: tcp
      - port: 47760
        proto: tcp
      - port: 47761
        proto: tcp
      - port: 47762
        proto: tcp
      - port: 47763
        proto: tcp
      - port: 47764
        proto: tcp
      - port: 47765
        proto: tcp
    # END UFW variables

    - zkg_packages:
        - ja3
        - bzar
  roles:
    - cluster 
