---
- hosts: all
  become: yes
  vars_files:
    - vault/geoip_vars.yml
  vars:
    - use_proxy: no
    - proxy_ip: x.x.x.x
    - proxy_port: 3128
    - zeek_ver: zeek-4.0.1
      # select the branch version of zeek to install
    - repo_branch: 'release/4.0'
    - digest_salt: h3ll0fr3ind
    - enable_json: yes
    - logdir: /zeeklogdir
    - zeekdir: /opt/zeek
    - spooldir: /zeekspooldir
    - LogExpireInterval: 14
    - StatsLogExpireInterval: 30
    - CrashExpireInterval: 30

    # UFW variables
    - ports_allowed:
      - port: ssh
      - port: 47760
        proto: tcp
      - port: 47761
        proto: tcp
      - port: 47762
        proto: tcp
      - port: 47763
        proto: tcp
      - port: 47764
        proto: tcp
      - port: 47765
        proto: tcp
    # END UFW variables

    - zkg_packages:
        - ja3
        - bzar
        - zeek-community-id
        - hassh
    - node_configuration:
        - name: zeek-manager
          type: manager
          host: localhost
        - name: zeek-proxy
          type: proxy
          host: localhost
        - name: zeek-logger
          type: logger
          host: localhost
    - worker_node_configuration:
        - name: zeek-worker-1
          pfring_interface: enp1s0f0
          worker_threads: 2
          host: localhost
#        - name: zeek-worker-2
#          pfring_interface: eth0
#          worker_threads: 3
#          host: localhost
  roles:
    - cluster
