---
- hosts: all
  become: yes
  vars:
    - zeek_ver: zeek-3.2.3
    - zeek_user: zeek
    - geoip_account: #geoip_account_number
    - geoip_license: #geoip_license
    - paths:
        - logpath: /zeek
          zeekpath: /opt/zeek
    - cpu_cores: 4

  roles:
    - cluster 
