---
- name: copy lab setcap plugin to /opt/zeek/lib/zeekctl/plugins/
  copy:
    src: setcap.py
    dest: /opt/zeek/lib/zeek/plugins/
    owner: zeek
    group: zeek
    mode: '0640'
  when: 
    - "'manager' in group_names"

- name: Append zeekctl plugin lines to zeekctl.cfg
  blockinfile:
     path: "{{ zeekdir }}/zeek/etc/zeekctl.cfg"
     block:  |
       setcap.enabled=1
       setcap.command=sudo /sbin/setcap cap_net_raw,cap_net_admin=eip /opt/zeek/bin/zeek && sudo /sbin/setcap cap_net_raw,cap_net_admin=eip /opt/zeek/bin/capstats
     insertafter: EOF
  when: 
    - "'manager' in group_names"

- name: create node.cfg
  template:
    src: node.cfg
    dest: /opt/zeek/etc/node.cfg
    owner: zeek
    group: zeek
    mode: '0640'
  with_nested: 
    - '{{ node_configuration }}'
    - '{{ worker_node_configuration }}'
  when: 
    - "'manager' in group_names"

- name: update digest_salt
  lineinfile:
     path: "{{ zeekdir }}/zeek/share/zeek/site/local.zeek"
     line: 'redef digest_salt = "{{ digest_salt }}";'
     regexp: ^redef\sdigest_salt\s=
  when: 
    - "'manager' in group_names"

- name: enable json output
  lineinfile:
     path: "{{ zeekdir }}/zeek/share/zeek/site/local.zeek"
     line: "@load policy/tuning/json-logs.zeek"
  when: 
    - "'manager' in group_names"
    - "enable_json"

- name: create spool directory for logdir
  file:
    path: "{{ logdir }}/zeek/spool"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes

- name: create logs directory for logdir
  file:
    path: "{{ logdir }}/zeek/logs"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes
