---
- name: copy setcap plugin to /opt/zeek/lib/zeekctl/plugins/
  copy:
    src: setcap.py
    dest: "{{ zeekdir }}/lib/zeek/plugins/"
    owner: zeek
    group: zeek
    mode: '0640'
  when:
    - "'manager' in group_names"

- name: Append zeekctl plugin lines to zeekctl.cfg
  blockinfile:
    path: "{{ zeekdir }}/etc/zeekctl.cfg"
    block: |
      setcap.enabled=1
      setcap.command=sudo /sbin/setcap cap_net_raw,cap_net_admin=eip /opt/zeek/bin/zeek && sudo /sbin/setcap cap_net_raw,cap_net_admin=eip /opt/zeek/bin/capstats
    insertafter: EOF
  when:
    - "'manager' in group_names"

- name: build node.cfg from jinja2 template
  template:
    src: node.cfg
    dest: "{{ zeekdir }}/etc/node.cfg"
    owner: zeek
    group: zeek
    mode: '0640'
  with_nested:
    - '{{ node_configuration }}'
    - '{{ worker_node_configuration }}'
  when:
    - "'manager' in group_names"

- name: update digest_salt
  lineinfile:
    path: "{{ zeekdir }}/share/zeek/site/local.zeek"
    line: 'redef digest_salt = "{{ digest_salt }}";'
    regexp: ^redef\sdigest_salt\s=
  when:
    - "'manager' in group_names"

- name: set log retention in days
  lineinfile:
    path: "{{ zeekdir }}/etc/zeekctl.cfg"
    line: 'LogExpireInterval = {{ LogExpireInterval }}'
    regexp: ^LogExpireInterval\s=
  when:
    - "'manager' in group_names"

- name: set crash log retention in days
  lineinfile:
    path: "{{ zeekdir }}/etc/zeekctl.cfg"
    line: 'CrashExpireInterval = {{ CrashExpireInterval }}'
    regexp: ^CrashExpireInterval\s=
  when:
    - "'manager' in group_names"

- name: set stats log retention in days
  lineinfile:
    path: "{{ zeekdir }}/etc/zeekctl.cfg"
    line: 'StatsLogExpireInterval = {{ StatsLogExpireInterval }}'
    regexp: ^StatsLogExpireInterval\s=
  when:
    - "'manager' in group_names"

- name: enable json output
  lineinfile:
    path: "{{ zeekdir }}/share/zeek/site/local.zeek"
    line: "@load policy/tuning/json-logs.zeek"
  when:
    - "'manager' in group_names"
    - "enable_json"

- name: create spool directory for logdir
  file:
    path: "{{ spooldir }}"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes

- name: create logs directory for logdir
  file:
    path: "{{ logdir }}"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes
