---
- name: install dependencies
  apt:
    name:
      - cmake
      - make
      - gcc
      - g++
      - flex
      - bison
      - libpcap-dev
      - libssl-dev
      - swig
      - zlib1g-dev
      - libmaxminddb-dev
      - postfix
      - gdb
      - python3-pip
      - python3
      - python3-dev
      - python3-git
      - python3-semantic-version
      - google-perftools
      - libgoogle-perftools-dev
    state: latest
