---
- name: Add maxmind ppa
  apt_repository:
    repo: ppa:maxmind/ppa

- name: install geoipupdate
  apt:
    name: geoipupdate
    update_cache: yes

- name: update GeoIP.conf
  template:
     src: GeoIP.conf
     dest: /etc/GeoIP.conf
     owner: root
     group: root
     mode: '0644'
- name: configure geoipupdate cron on wednesday morning
  cron:
    name: weekly geo ip database update
    user: root
    weekday: '3'
    hour: '3'
    minute: '0'
    job: geoipupdate
