---
- name: Add maxmind ppa
  apt_repository:
    repo: ppa:maxmind/ppa
  when: "'manager' in group_names"

- name: install geoipupdate
  apt:
    name: geoipupdate
    update_cache: yes
  when: "'manager' in group_names"

- name: update GeoIP.conf
  template:
     src: GeoIP.conf
     dest: /etc/GeoIP.conf
     owner: root
     group: root
     mode: '0644'
  when: "'manager' in group_names"

- name: configure geoipupdate cron on wednesday morning
  cron:
    name: weekly geo ip database update
    user: root
    weekday: '3'
    hour: '3'
    minute: '0'
    job: geoipupdate
  when: "'manager' in group_names"

- name: run geoipupdate
  command: geoipupdate
  when: "'manager' in group_names"
