---
- name: install dependencies
  apt:
    name:
      - cmake
      - make
      - gcc
      - g++
      - flex
      - bison
      - libpcap-dev
      - libssl-dev
      - python-dev
      - swig
      - zlib1g-dev
      - libmaxminddb-dev
      - postfix
      - gdb
      - python-pip
    state: present

- name: create zeek user and group
  user:
    name: zeek
    shell: /bin/bash
    home: /home/zeek

- name: create dependent directories
  file:
    path: "{{ item }}"
    owner: zeek
    group: zeek
    state: directory
  with_items: "{{ paths }}"

- name: copy sudoers file for zeek nonroot user
  copy:
    src: zeek_sudoer
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: '0644'

- name: extract zeek to /home/zeek
  unarchive:
    src: "{{ zeek_ver }}.tar.gz"
    dest: /home/zeek
    owner: zeek
    group: zeek
  when: "'manager' in group_names"

- name: install zeek
  make:
    chdir: /home/zeek/{{ zeek_ver }}
    target: install
    params:
      NUM_THREADS: 4
  become_user: zeek
  when: "'manager' in group_names"
  async: 1000
  poll: 0
  register: make_zeek

- name: check on install zeek task
  async_status:
    jid: "{{ make_zeek.ansible_job_id }}"
  become_user: zeek
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 10
