---
- name: create zeek user and group
  user:
    name: zeek
    shell: /bin/bash
    home: /home/zeek

- name: display the var paths
  debug: var=paths

- name: create dependent directory for zeek
  file:
    path: "{{ item.zeekpath }}"
    owner: zeek
    group: zeek
    state: directory
  with_items: "{{ paths }}"

- name: create dependent directory for zeek logging
  file:
    path: "{{ item.logpath }}"
    owner: zeek
    group: zeek
    state: directory
  with_items: "{{ paths }}"

- name: copy sudoers file for zeek nonroot user
  copy:
    src: zeek_sudoer
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: '0644'
