---
- name: create zeek user and group
  user:
    name: zeek
    shell: /bin/bash
    home: /home/zeek
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: update zeek PATH
  lineinfile:
    path: /home/zeek/.bashrc
    insertafter: EOF
    line: PATH={{ zeekdir }}/zeek/bin:$PATH

- name: create dependent directory for zeekdir
  file:
    path: "{{ zeekdir }}"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes

- name: create logs directory for logdir
  file:
    path:
      - "{{ logdir }}/zeek"
    owner: zeek
    group: zeek
    state: directory
    recurse: yes

- name: copy sudoers file for zeek nonroot user
  copy:
    src: zeek_sudoer
    dest: /etc/sudoers.d/zeek
    owner: root
    group: root
    mode: '0644'

- name: grab pub key
    fetch:
      dest: zeek_id_rsa.pub
      src: /home/zeek/.ssh/id_rsa.pub
      flat: yes
  when:
    - "'manager' in group_names"

- name: set authorized key for zeek user on all servers
  authorized_key:
    user: zeek
    state: present
    key: "{{ lookup('file', 'zeek_id_rsa.pub') }}"
