---
- name: create {{ zeek_user }} and group
  user:
    name: "{{ zeek_user }}"
    shell: /bin/bash
    home: "/home/{{ zeek_user }}"

- name: display the var paths
  debug: var=paths

- name: create dependent directory for zeek
  file:
    path: "{{ item.zeekpath }}"
    owner: "{{ zeek_user }}"
    group: "{{ zeek_user }}"
    state: directory
  with_items: "{{ paths }}"

- name: create dependent directory for zeek logging
  file:
    path: "{{ item.logpath }}"
    owner: "{{ zeek_user }}"
    group: "{{ zeek_user }}"
    state: directory
  with_items: "{{ paths }}"

- name: copy sudoers file for zeek nonroot user
  template:
    src: zeek_sudoer
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: '0644'
